[package]
name = "chardet14_release_profiles"
version = "0.1.0"
edition = "2021"
description = "test"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
